<pre>
<center><b><h2>Week 1 Task</h2></b></center>
<pre>

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [20]:
df = pd.read_csv("cardio_train.csv", sep=";")
df

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [23]:
df.shape

(70000, 13)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [27]:
df.describe()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,49972.419900,19468.865814,1.349571,164.359229,74.205690,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,28851.302323,2467.251667,0.476838,8.210126,14.395757,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,10798.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25006.750000,17664.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,50001.500000,19703.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,74889.250000,21327.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,99999.000000,23713.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

In [29]:
df.isnull().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [31]:
df.head(5)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [33]:
df.tail(5)

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
69995,99993,19240,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,22601,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,19066,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,22431,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,20540,1,170,72.0,120,80,2,1,0,0,1,0

In [35]:
a= df.columns
for i in a:
    print(i)

id
age
gender
height
weight
ap_hi
ap_lo
cholesterol
gluc
smoke
alco
active
cardio

In [37]:
df.groupby('weight').max()

,id,age,gender,height,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
weight,,,,,,,,,,,,
10.0,82567,18804,2,165,180,1100,2,2,0,0,1,1
11.0,48318,21582,2,178,130,90,1,1,0,0,1,1
21.0,85931,21855,1,162,120,80,2,1,0,0,1,1
22.0,42156,20408,2,177,120,80,1,1,1,1,1,0
23.0,38312,23284,1,157,110,80,1,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
178.0,88220,20656,2,165,140,90,3,3,1,1,1,1
180.0,87612,18975,2,196,140,100,3,2,0,0,1,1
181.0,52564,19630,1,161,180,1100,2,1,0,0,1,1
183.0,87498,20939,2,180,110,80,3,3,0,1,1,1
200.0,71945,16765,2,186,150,90,1,1,0,0,1,1

In [39]:
df['age'].value_counts()

age
19741    32
18236    32
20376    31
18253    31
20442    31
         ..
19277     1
16493     1
20059     1
23659     1
17926     1
Name: count, Length: 8076, dtype: int64

In [41]:
np.mean(df['age'])

19468.865814285713

In [43]:
np.median(df['age'])

19703.0

In [45]:
np.std(df['age'])

2467.2340439522563

In [47]:
np.min(df['height'])

55

In [49]:
np.max(df['weight'])

200.0

In [51]:
heights = np.array(df['height'])
np.mean(heights)
np.median(heights)
np.std(heights)

8.210067720568848

In [53]:
print("normal cholesterol: ",(df['cholesterol']==1).sum())
print("normal cholesterol: ",(df['cholesterol']==2).sum())
print("normal cholesterol: ",(df['cholesterol']==3).sum())

normal cholesterol:  52385
normal cholesterol:  9549
normal cholesterol:  8066

In [55]:
print("No of Smoker & drink alcohol: ", ((df['smoke'] == 1) & (df['alco'] == 1)).sum())

print("No of Non-Smoker & dont drink ALcohol: ", ((df['smoke'] == 0) & (df['alco'] == 0)).sum())

No of Smoker & drink alcohol:  1854
No of Non-Smoker & dont drink ALcohol:  61921

<pre>
<center><b><h2>Week 2 Task</h2></b></center>
<pre>

In [57]:
df.isnull().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [59]:
df.duplicated().sum()

0

In [61]:
df['age'] = (df['age'] // 365).astype(int)
df

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,50,2,168,62.0,110,80,1,1,0,0,1,0
1,1,55,1,156,85.0,140,90,3,1,0,0,1,1
2,2,51,1,165,64.0,130,70,3,1,0,0,0,1
3,3,48,2,169,82.0,150,100,1,1,0,0,1,1
4,4,47,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,52,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,61,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,52,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,61,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,56,1,170,72.0,120,80,2,1,0,0,1,0

In [63]:
df.rename(columns={
    'ap_hi': 'systolic_bp',
    'ap_lo': 'diastolic_bp'
}, inplace=True)
df

,id,age,gender,height,weight,systolic_bp,diastolic_bp,cholesterol,gluc,smoke,alco,active,cardio
0,0,50,2,168,62.0,110,80,1,1,0,0,1,0
1,1,55,1,156,85.0,140,90,3,1,0,0,1,1
2,2,51,1,165,64.0,130,70,3,1,0,0,0,1
3,3,48,2,169,82.0,150,100,1,1,0,0,1,1
4,4,47,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,52,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,61,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,52,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,61,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,56,1,170,72.0,120,80,2,1,0,0,1,0

In [65]:
df = df.loc[(df['height'] >= 120) & (df['height'] <= 220)]
df = df.loc[(df['weight'] >= 40) & (df['weight'] <= 200)]

In [67]:
df

,id,age,gender,height,weight,systolic_bp,diastolic_bp,cholesterol,gluc,smoke,alco,active,cardio
0,0,50,2,168,62.0,110,80,1,1,0,0,1,0
1,1,55,1,156,85.0,140,90,3,1,0,0,1,1
2,2,51,1,165,64.0,130,70,3,1,0,0,0,1
3,3,48,2,169,82.0,150,100,1,1,0,0,1,1
4,4,47,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,52,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,61,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,52,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,61,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,56,1,170,72.0,120,80,2,1,0,0,1,0

In [69]:
df = df.loc[(df['systolic_bp'] >= 80) & (df['systolic_bp'] <= 250)]
df = df.loc[(df['diastolic_bp'] >= 40) & (df['diastolic_bp'] <= 160)]
df = df.loc[df['systolic_bp'] >= df['diastolic_bp']]
df

,id,age,gender,height,weight,systolic_bp,diastolic_bp,cholesterol,gluc,smoke,alco,active,cardio
0,0,50,2,168,62.0,110,80,1,1,0,0,1,0
1,1,55,1,156,85.0,140,90,3,1,0,0,1,1
2,2,51,1,165,64.0,130,70,3,1,0,0,0,1
3,3,48,2,169,82.0,150,100,1,1,0,0,1,1
4,4,47,1,156,56.0,100,60,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,99993,52,2,168,76.0,120,80,1,1,1,0,1,0
69996,99995,61,1,158,126.0,140,90,2,2,0,0,1,1
69997,99996,52,2,183,105.0,180,90,3,1,0,1,0,1
69998,99998,61,1,163,72.0,135,80,1,2,0,0,0,1
69999,99999,56,1,170,72.0,120,80,2,1,0,0,1,0

In [71]:
cleandf = df.drop_duplicates(
    subset=df.columns.drop('id'),
    keep='first'
)

print("Original shape:", df.shape)
print("After duplicate:", cleandf.shape)

Original shape: (68567, 13)
After duplicate: (65361, 13)

In [73]:
cleandf.loc[:, 'BMI'] = cleandf['weight'] / ((cleandf['height']/100) ** 2)
cleandf

C:\Users\Riya\AppData\Local\Temp\ipykernel_22996\3837192886.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleandf.loc[:, 'BMI'] = cleandf['weight'] / ((cleandf['height']/100) ** 2)

,id,age,gender,height,weight,systolic_bp,diastolic_bp,cholesterol,gluc,smoke,alco,active,cardio,BMI
0,0,50,2,168,62.0,110,80,1,1,0,0,1,0,21.967120
1,1,55,1,156,85.0,140,90,3,1,0,0,1,1,34.927679
2,2,51,1,165,64.0,130,70,3,1,0,0,0,1,23.507805
3,3,48,2,169,82.0,150,100,1,1,0,0,1,1,28.710479
4,4,47,1,156,56.0,100,60,1,1,0,0,0,0,23.011177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69994,99992,57,1,165,80.0,150,80,1,1,0,0,1,1,29.384757
69996,99995,61,1,158,126.0,140,90,2,2,0,0,1,1,50.472681
69997,99996,52,2,183,105.0,180,90,3,1,0,1,0,1,31.353579
69998,99998,61,1,163,72.0,135,80,1,2,0,0,0,1,27.099251
69999,99999,56,1,170,72.0,120,80,2,1,0,0,1,0,24.913495

In [66]:
cleandf.reset_index(drop=True, inplace=True)
cleandf

,id,age,gender,height,weight,systolic_bp,diastolic_bp,cholesterol,gluc,smoke,alco,active,cardio,BMI
0,0,50,2,168,62.0,110,80,1,1,0,0,1,0,21.967120
1,1,55,1,156,85.0,140,90,3,1,0,0,1,1,34.927679
2,2,51,1,165,64.0,130,70,3,1,0,0,0,1,23.507805
3,3,48,2,169,82.0,150,100,1,1,0,0,1,1,28.710479
4,4,47,1,156,56.0,100,60,1,1,0,0,0,0,23.011177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65356,99992,57,1,165,80.0,150,80,1,1,0,0,1,1,29.384757
65357,99995,61,1,158,126.0,140,90,2,2,0,0,1,1,50.472681
65358,99996,52,2,183,105.0,180,90,3,1,0,1,0,1,31.353579
65359,99998,61,1,163,72.0,135,80,1,2,0,0,0,1,27.099251
65360,99999,56,1,170,72.0,120,80,2,1,0,0,1,0,24.913495

In [75]:
cleandf[['age', 'height']].corr()

             age    height
age     1.000000 -0.087604
height -0.087604  1.000000

<pre>
<center><b><h2>Week 3 Task</h2></b></center>
<pre>

In [71]:
cleandf.to_csv('cardio_preprocessed.csv', index=False)

In [77]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [4]:
data = pd.read_csv('cardio_preprocessed.csv')
data

,id,age,gender,height,weight,systolic_bp,diastolic_bp,cholesterol,gluc,smoke,alco,active,cardio,BMI
0,0,50,2,168,62.0,110,80,1,1,0,0,1,0,21.967120
1,1,55,1,156,85.0,140,90,3,1,0,0,1,1,34.927679
2,2,51,1,165,64.0,130,70,3,1,0,0,0,1,23.507805
3,3,48,2,169,82.0,150,100,1,1,0,0,1,1,28.710479
4,4,47,1,156,56.0,100,60,1,1,0,0,0,0,23.011177
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65356,99992,57,1,165,80.0,150,80,1,1,0,0,1,1,29.384757
65357,99995,61,1,158,126.0,140,90,2,2,0,0,1,1,50.472681
65358,99996,52,2,183,105.0,180,90,3,1,0,1,0,1,31.353579
65359,99998,61,1,163,72.0,135,80,1,2,0,0,0,1,27.099251
65360,99999,56,1,170,72.0,120,80,2,1,0,0,1,0,24.913495

In [7]:
import sklearn

In [9]:
X = data.drop(columns=["id", "cardio"])
y = data["cardio"]

In [11]:
X

,age,gender,height,weight,systolic_bp,diastolic_bp,cholesterol,gluc,smoke,alco,active,BMI
0,50,2,168,62.0,110,80,1,1,0,0,1,21.967120
1,55,1,156,85.0,140,90,3,1,0,0,1,34.927679
2,51,1,165,64.0,130,70,3,1,0,0,0,23.507805
3,48,2,169,82.0,150,100,1,1,0,0,1,28.710479
4,47,1,156,56.0,100,60,1,1,0,0,0,23.011177
...,...,...,...,...,...,...,...,...,...,...,...,...
65356,57,1,165,80.0,150,80,1,1,0,0,1,29.384757
65357,61,1,158,126.0,140,90,2,2,0,0,1,50.472681
65358,52,2,183,105.0,180,90,3,1,0,1,0,31.353579
65359,61,1,163,72.0,135,80,1,2,0,0,0,27.099251
65360,56,1,170,72.0,120,80,2,1,0,0,1,24.913495

In [13]:
y

0        0
1        1
2        1
3        1
4        0
        ..
65356    1
65357    1
65358    1
65359    1
65360    0
Name: cardio, Length: 65361, dtype: int64

In [83]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

## Logistic Regression

In [86]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

logistic = LogisticRegression(max_iter=1000)
logistic.fit(X_train, y_train)

y_pred_tt = logistic.predict(X_test)
acc_tt = accuracy_score(y_test, y_pred_tt)

print("Logistic:Train-Test Split Accuracy:", acc_tt)

Logistic:Train-Test Split Accuracy: 0.7235453108266612

## Random-Forest

In [91]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

rf_tt = RandomForestClassifier(
    n_estimators=300,
    max_depth=10,
    min_samples_split=5,
    random_state=42
)


rf_tt.fit(X_train, y_train)

y_pred_tt = rf_tt.predict(X_test)
acc_tt_rf = accuracy_score(y_test, y_pred_tt)

print("Random Forest Train-Test Accuracy:", acc_tt_rf)

Random Forest Train-Test Accuracy: 0.7310418685297567

In [93]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

dt_tt = DecisionTreeClassifier(random_state=42)
dt_tt.fit(X_train, y_train)

y_pred_tt = dt_tt.predict(X_test)
acc_tt_dt = accuracy_score(y_test, y_pred_tt)

print("Decision Tree Train-Test Accuracy:", acc_tt_dt)

Decision Tree Train-Test Accuracy: 0.6150080318213111

In [111]:
from sklearn.tree import DecisionTreeClassifier
import pickle
final_model1 = DecisionTreeClassifier(
    criterion='entropy',
    max_depth=10,
    min_samples_split=5,
    random_state=42
)

In [117]:
final_model1.fit(X, y)

DecisionTreeClassifier(criterion='entropy', max_depth=10, min_samples_split=5,
                       random_state=42)

In [119]:
final_model2 = LogisticRegression(max_iter=5000)
final_model2.fit(X,y)

LogisticRegression(max_iter=5000)

In [105]:
from sklearn.ensemble import RandomForestClassifier
import pickle

final_model3 = RandomForestClassifier(
    n_estimators=100,
    criterion='entropy',
    max_depth=10,
    min_samples_split=5,
    random_state=42
)

In [109]:
final_model3.fit(X, y)

RandomForestClassifier(criterion='entropy', max_depth=10, min_samples_split=5,
                       random_state=42)

In [123]:
import pickle

with open("heart_disease_model.pkl", "wb") as file:
    pickle.dump(final_model2, file)

print("Pickle file created successfully!")

Pickle file created successfully!